my_tuple=(1,2,3,'a','b','c')
print(my_tuple[0])
print(my_tuple[3])
print(my_tuple[1:4])
print(my_tuple[:3])
print(my_tuple[3:])
print(len(my_tuple))
tuple1=(1,2,3)
tuple2=('a','b','c')
concatenated_tuple=tuple1+tuple2
print(concatenated_tuple)
repeated_tuple=(1,2)*3
print(repeated_tuple)
tuple3=('John','Doe',25)
first_name,last_name,age=tuple3
print(first_name)
print(last_name)
print(age)
